# Configuration of Hugo
# Guide: https://sourcethemes.com/academic/docs/get-started/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
#
# This file is formatted using TOML syntax - learn more at https://learnxinyminutes.com/docs/toml/
# Each configuration section is defined by a name in square brackets (e.g. `[outputs]`).
baseURL = "https://david-menendez.netlify.app/"
title = "David Menendez"
theme = "wowchemy"
defaultContentLanguage = "en"
hasCJKLanguage = false

# Enable syntax highlighting for code
pygmentsUseClasses = true
pygmentsCodeFences = true

# Enable asset minification
minify = true

[params]
  # Website identity
  description = "A modern academic website"
  date_format = "2006-01-02"

  # SEO
  seo.use_schema = true
  seo.site_type = "Person"
  seo.name = "Your Name"

  # Site author info
  author = "Your Name"

# Main menu
[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Publications"
    url = "/publication/"
    weight = 2

  [[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = 3

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

# Enable output formats
[outputs]
  home = ["HTML", "RSS", "JSON"]

# Install Wowchemy
[module]
  [[module.imports]]
    path = "github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-reveal"
    path = "github.com/HugoBlox/hugo-blox-builder/modules/blox-bootstrap/v5"
